### ISSUE TITLE
Cambio de año en novedades de suspensión - TITAN

### ISSUE THREAD

**Issue by a52290451** [udistrital/titan_cliente#210]
Se requiere ajustar la novedad de suspensión para atender los casos en que la novedad cambia de año (la feche de inio y fin se encuentran en años diferentes).

**Criterios de acpetación**

- [x] Desarrollo en local.
- [x] Pruebas funcionales en local.
- [x] Creación de rama Feat.
- [x] PR en rama develop.
- [x] PR en rama release.
- [x] Pruebas funcionales en ambiente de pruebas.
- [x] Checklist de despliegue en producción.
- [x] PR a rama master.
- [ ] Estabilización del sistema en produccion.

Nota: se adjunta formato de [checklist](https://docs.google.com/document/d/1YvTCgQYu2KLopo0rmLpZW0wjslwEcPCC/edit) para despliegue a producción.

**Comment by diagutierrezro** [comment]
Este cambio no requiere checklist
