### ISSUE TITLE
Corrección - bugs de novedades de cesión - TITAN

### ISSUE THREAD

**Issue by a52290451** [udistrital/titan_cliente#211]
Se requiere corregir bugs asociados a novedades de cesión en cuanto a crear cesiones en el mes de finalización del contrato y al realizar una cesión despues de una novedad de Otro Si.

**Criterios de acpetación**

- [x] Desarrollo en local.
- [x] Pruebas funcionales en local.
- [x] Creación de rama Feat.
- [x] PR en rama develop.
- [x] PR en rama release.
- [x] Pruebas funcionales en ambiente de pruebas.
- [x] Checklist de despliegue en producción.
- [x] PR a rama master.
- [x] Estabilización del sistema en produccion.

Nota: se adjunta formato de [checklist](https://docs.google.com/document/d/1YvTCgQYu2KLopo0rmLpZW0wjslwEcPCC/edit) para despliegue a producción.

**Comment by diagutierrezro** [comment]
No se requiere checklist
