### ISSUE TITLE
Documentación asociada a cambio de vigencia.

### ISSUE THREAD

**Issue by a52290451** [udistrital/titan_cliente#212]
Se requiere elaborar documento asociado al análisis de ajuste de rubros para cuando se ejecute el cambio de vigencia.

**Criterios de aceptación**

- [x] Documento con análisis realizado.

**Comment by diagutierrezro** [comment]
Se crea el documento con valores a tener en cuenta para cuando se realice el cambio de vigencia https://docs.google.com/spreadsheets/d/1Z1uhAaMAIvRwyCj8c4_uehys67KeNRoKbM7EinM31LA/edit?usp=sharing
